start: (toyota|honda)

toyota: (TOYOTA_BRAND|TOYOTA_MODEL|COLOR|TOYOTA_UNK)+
TOYOTA_BRAND: "toyota"
TOYOTA_MODEL: AVANZA|INNOVA
AVANZA: "avanza"
INNOVA: "innova"
TOYOTA_UNK.-1: /[a-zA-Z0-9\:]+/

honda: (HONDA_BRAND|HONDA_MODEL|COLOR|HONDA_UNK)+
HONDA_BRAND: "honda"
HONDA_MODEL: JAZZ|BRIO
JAZZ: "jazz"
BRIO: "brio"
HONDA_UNK.-1: /[a-zA-Z0-9\:]+/

COLOR: WHITE|RED
WHITE: "white"
RED: "red"

%import common.WS
%ignore WS
